# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ece40a2f111c7cb448b160cb4df1a5bca22634e348ad46d0a125b1f0e23b7a5c58a658d3797d8f4b6ab050650a3783217fa1153ad130238696b85f6bb92319f3

test:
  secret_key_base: 266ddd16ac20ded6185d0f667f31e605d93ed2291eb3328d9905ae86f44a9ad6467cdb102fe96781ab8d05b24236ef0675f506115cf2da06191c04b8a0bafb2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
